Add check action

diff --git a/.github/workflows/check-start-windows.yml b/.github/workflows/check-start-windows.yml
--- a/.github/workflows/check-start-windows.yml
+++ b/.github/workflows/check-start-windows.yml
@@ -22,19 +22,19 @@ jobs:
     - name: Write vault password file
       run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/vault_pass.txt
 
-      - name: Validate Ansible environment (path + version + python)
-        run: |
-          echo "=== PATH ==="
-          echo "$PATH"
-          echo
-          echo "=== which ansible-playbook ==="
-          which ansible-playbook || echo "NOT FOUND"
-          echo
-          echo "=== ansible --version ==="
-          ansible --version || echo "ANSIBLE FAILED"
-          echo
-          echo "=== which python ==="
-          which python
+    - name: Validate Ansible environment (path + version + python)
+      run: |
+        echo "=== PATH ==="
+        echo "$PATH"
+        echo
+        echo "=== which ansible-playbook ==="
+        which ansible-playbook || echo "NOT FOUND"
+        echo
+        echo "=== ansible --version ==="
+        ansible --version || echo "ANSIBLE FAILED"
+        echo
+        echo "=== which python ==="
+        which python
 
     - name: Start windows-service.yml
       run: |
